spring:
  application:
    name: stock-data-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8088}"
logging:
  config: "${CONFIG_SERVER_URL:http://localhost:8088}/default/default/default/logback-spring.xml"