server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8061}/eureka/
  instance:
    hostname: ${SERVICE_NAME:localhost}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: org.finance.stockapp.stock

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${DATABASE_SERVICE:localhost}:5432/market-db
    username: admin
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create-drop


management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans