server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8061}/eureka/
  instance:
    hostname: ${SERVICE_NAME:localhost}

springdoc:
  packagesToScan: org.finance.stockapp.stock

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:7000}/realms/stockapp/protocol/openid-connect/certs
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${DATABASE_SERVICE:localhost}:5432/market_db
    username: admin
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view=false: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
      spring:
        jpa:
          open-in-view: false

logging:
  config: "${CONFIG_SERVER_URL:http://localhost:8088}/default/default/default/logback-spring.xml"
  logstash-url: ${LOGSTASH_SERVER_URL:localhost:5044}