spring:
  application:
    name: stock-quote-producer
  config:
    import:
      - "configserver:${CONFIG_SERVER_URL:http://localhost:8088}"
      - "configserver:${CONFIG_SERVER_URL:http://localhost:8088}/api-key"
logging:
  config: "${CONFIG_SERVER_URL:http://localhost:8088}/default/default/default/logback-spring.xml"