version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: localhost
    ports:
      - 7000:7000
    volumes:
      - ./keycloak/stockapp-realm-export.json:/opt/keycloak/data/import/stockapp-realm-export.json
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_HEALTH_ENABLED=true"
      - "KC_METRICS_ENABLED=true"
      - "KC_HTTP_PORT=7000"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://postgres/keycloak_db"
      - "KC_DB_USERNAME=admin"
      - "KC_DB_PASSWORD=password"
    restart: always
    command: [ "start-dev", "--import-realm" ]
    networks:
      - ${GLOBAL_NETWORK:-keycloak}
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/7000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'" ]
      start_period: 40s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy      
 