version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: localhost
    ports:
      - 7000:7000
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
      - "KC_HEALTH_ENABLED=true"
      - "KC_METRICS_ENABLED=true"
      - "KC_HTTP_PORT=7000"
      - "KC_DB=postgres"
      - "KC_DB_URL=jdbc:postgresql://postgres/keycloak_db"
      - "KC_DB_USERNAME=admin"
      - "KC_DB_PASSWORD=password"
    restart: always
    command:
      - "start-dev"
    networks:
      - ${GLOBAL_NETWORK:-keycloak}
    depends_on:
      postgres:
        condition: service_healthy      
 