version: "3.7"
volumes:
  keycloak:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    hostname: localhost
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    volumes:
      - keycloak:/opt/keycloak/data/
    restart: always
    command:
      - "start-dev"
    networks:
      - ${GLOBAL_NETWORK:-keycloak}     
 