version: "3.8"
#volumes:
#  postgres:

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    ports:
      - 5432:5432
    volumes:
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    #  - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=market_db,keycloak_db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    networks:
      - ${GLOBAL_NETWORK:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -q -d market_db && pg_isready -U $$POSTGRES_USER -q -d keycloak_db" ]
      interval: 5s
      timeout: 10s
      retries: 10      
